export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_PROFILE_DATA = "SET_USER_PROFILE_DATA";
export const CHANGE_THEME = "CHANGE_THEME";
export const FETCH_USER_PROFILE_DATA_SUCCESS = "FETCH_USER_PROFILE_DATA_SUCCESS";
export const FETCH_USER_PROFILE_DATA_FAILURE = "FETCH_USER_PROFILE_DATA_FAILURE";